### ISSUE TITLE
Add Frontend code to this repo

### ISSUE THREAD

**Issue by zhaoxuyang13** [zhaoxuyang13/CapDetect#2]
python client using Qt.

**Comment by liuzhengwei127** [comment]
don't worry. after tomorrow's exam发自我的华为手机-------- 原始邮件 --------发件人： MizihaxiZhao <notifications@github.com>日期： 2019年12月30日周一 晚上10:22收件人： zhaoxuyang13/CapDetect <CapDetect@noreply.github.com>抄送： 五柳寄书 <756670011@qq.com>, Assign <assign@noreply.github.com>主    题： Re: [zhaoxuyang13/CapDetect] Add Frontend code to this repo (#2)Assigned #2 to @liuzhengwei127.

**Comment by zhaoxuyang13** [comment]
ok
